In [1]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

NameError: name 'np' is not defined

In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame


In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [4]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
type(x)

numpy.ndarray

In [7]:
x.shape

(2L, 3L)

In [8]:
list = [1,2,3,4]

In [9]:
list

[1, 2, 3, 4]

In [10]:
array= np.array(list)

In [11]:
array

array([1, 2, 3, 4])

In [12]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [13]:
array = np.ones(4)

In [14]:
array

array([ 1.,  1.,  1.,  1.])

In [15]:
arr = array.copy()

In [16]:
arr

array([ 1.,  1.,  1.,  1.])

In [17]:
array

array([ 1.,  1.,  1.,  1.])

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
np.arange(50).reshape((10,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [22]:
np.arange(10).reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
np.empty((6,2))

array([[  8.74496193e-322,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000]])

In [26]:
arr2d=[[2,4,6,8]]

In [27]:
arr2d

[[2, 4, 6, 8]]

In [28]:
type(arr2d)

list

In [29]:
dtype(arr2d)

NameError: name 'dtype' is not defined